/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        canvas: '#f7f5f2',
        'canvas-elevated': '#ffffff',
        surface: '#ffffff',
        'surface-soft': '#efece7',
        hairline: '#e4e0d9',
        'hairline-strong': '#d3cdc2',

        ink: '#211f1c',
        'ink-secondary': '#4a463f',
        'ink-muted': '#847d72',
        'ink-faint': '#b3aca0',
        'on-dark': '#f7f5f2',

        'brand-yellow': '#ffd02f',
        'brand-yellow-deep': '#fcb900',
        'yellow-soft': '#fff4c4',
        'ink-on-yellow': '#211f1c',

        'accent-teal': '#0fbcb0',
        'teal-soft': '#c3faf5',
        'accent-coral': '#ff9999',
        'coral-soft': '#ffe0e0',
        'accent-rose': '#f6b6e8',
        'rose-soft': '#fde0f0',
        'accent-sky': '#62aef0',
        'sky-soft': '#dcecfc',

        success: '#00b473',
        'success-soft': '#d7f5e8',
        warning: '#dd5b00',
        'warning-soft': '#ffe6cd',
        error: '#d64545',
        'error-soft': '#fbdcdc',

        'canvas-dark': '#18140f',
        'surface-dark': '#241f18',
        'hairline-dark': '#3a342a',
        'ink-dark': '#f2ede4',
        'ink-secondary-dark': '#c9c1b3',
      },
      fontFamily: {
        heading: ['Fraunces'],
        sans: ['Inter'],
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '28px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        xxl: '32px',
        xxxl: '40px',
        section: '48px',
      },
      fontSize: {
        'heading-1': ['24px', { lineHeight: '30px' }],
        'heading-2': ['20px', { lineHeight: '26px' }],
        'heading-3': ['17px', { lineHeight: '22px' }],
        title: ['16px', { lineHeight: '22px' }],
        'body-md': ['15px', { lineHeight: '22px' }],
        'body-sm': ['13px', { lineHeight: '18px' }],
        caption: ['12px', { lineHeight: '16px' }],
        eyebrow: ['11px', { lineHeight: '14px', letterSpacing: '0.4px' }],
        button: ['15px', { lineHeight: '20px' }],
      },
    },
  },
  plugins: [],
};
